// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.Sqlite;
using Microsoft.Extensions.AI;
using Microsoft.Extensions.VectorData;
using Microsoft.Extensions.VectorData.ProviderServices;
using CommunityToolkit.VectorData.SqliteVec;
using Xunit;

namespace SqliteVec.UnitTests;

/// <summary>
/// Unit tests for <see cref="SqliteCommandBuilder"/> class.
/// </summary>
public sealed class SqliteCommandBuilderTests : IDisposable
{
    private readonly SqliteCommand _command;
    private readonly SqliteConnection _connection;

    public SqliteCommandBuilderTests()
    {
        this._command = new() { Connection = this._connection };
        this._connection = new();
    }

    [Fact]
    public void ItBuildsTableCountCommand()
    {
        // Arrange
        const string TableName = "TestTable";

        // Act
        var command = SqliteCommandBuilder.BuildTableCountCommand(this._connection, TableName);

        // Assert
        Assert.Equal("SELECT count(*) FROM sqlite_master WHERE type='table' AND name=@tableName;", command.CommandText);
        Assert.Equal("@tableName", command.Parameters[0].ParameterName);
        Assert.Equal(TableName, command.Parameters[0].Value);
    }

    [Theory]
    [InlineData(true)]
    [InlineData(false)]
    public void ItBuildsCreateTableCommand(bool ifNotExists)
    {
        // Arrange
        const string TableName = "TestTable";

        var columns = new List<SqliteColumn>
        {
            new("Column1", "Type1", isPrimary: true),
            new("Column2", "Type2", isPrimary: false) { IsNullable = true, Configuration = new() { ["distance_metric"] = "l2" } },
            new("Column3", "Type3", isPrimary: false) { IsNullable = false },
            new("Column4", "Type4", isPrimary: false) { IsNullable = true },
        };

        // Act
        var command = SqliteCommandBuilder.BuildCreateTableCommand(this._connection, TableName, columns, ifNotExists);

        // Assert
        Assert.Contains("CREATE TABLE", command.CommandText);
        Assert.Contains(TableName, command.CommandText);

        Assert.Equal(ifNotExists, command.CommandText.Contains("IF NOT EXISTS"));

        Assert.Contains("\"Column1\" Type1 PRIMARY KEY", command.CommandText);
        Assert.Contains("\"Column2\" Type2 distance_metric=l2", command.CommandText);
        Assert.Contains("\"Column3\" Type3 NOT NULL", command.CommandText);
        Assert.Contains("\"Column4\" Type4", command.CommandText);
        Assert.DoesNotContain("\"Column4\" Type4 NOT NULL", command.CommandText);
    }

    [Theory]
    [InlineData(true)]
    [InlineData(false)]
    public void ItBuildsCreateVirtualTableCommand(bool ifNotExists)
    {
        // Arrange
        const string TableName = "TestTable";

        var columns = new List<SqliteColumn>
        {
            new("Column1", "Type1", isPrimary: true),
            new("Column2", "Type2", isPrimary: false) { IsNullable = true, Configuration = new() { ["distance_metric"] = "l2" } },
        };

        // Act
        var command = SqliteCommandBuilder.BuildCreateVirtualTableCommand(this._connection, TableName, columns, ifNotExists);

        // Assert
        Assert.Contains("CREATE VIRTUAL TABLE", command.CommandText);
        Assert.Contains(TableName, command.CommandText);
        Assert.Contains("USING vec0", command.CommandText);

        Assert.Equal(ifNotExists, command.CommandText.Contains("IF NOT EXISTS"));

        Assert.Contains("Column1 Type1 PRIMARY KEY", command.CommandText);
        Assert.Contains("Column2 Type2 distance_metric=l2", command.CommandText);
    }

    [Fact]
    public void ItBuildsDropTableCommand()
    {
        // Arrange
        const string TableName = "TestTable";

        // Act
        var command = SqliteCommandBuilder.BuildDropTableCommand(this._connection, TableName);

        // Assert
        Assert.Equal("DROP TABLE IF EXISTS \"TestTable\";", command.CommandText);
    }

    [Theory]
    [InlineData(true)]
    [InlineData(false)]
    public void ItBuildsInsertCommand_without_autogenerated_key(bool replaceIfExists)
    {
        // Arrange
        const string TableName = "TestTable";

        var model = BuildModel(
        [
            new VectorStoreKeyProperty("Id", typeof(int)),
            new VectorStoreDataProperty("Name", typeof(string)),
            new VectorStoreDataProperty("Age", typeof(string)),
            new VectorStoreDataProperty("Address", typeof(string)),
        ]);

        var records = new List<Dictionary<string, object?>>
        {
            new() { ["Id"] = 1, ["Name"] = "NameValue1", ["Age"] = "AgeValue1", ["Address"] = "AddressValue1" },
            new() { ["Id"] = 2, ["Name"] = "NameValue2", ["Age"] = "AgeValue2", ["Address"] = "AddressValue2" },
        };

        // Act
        var command = SqliteCommandBuilder.BuildInsertCommand(
            this._connection,
            TableName,
            model,
            data: true,
            isRecordKeyDatabaseGenerated: false,
            replaceIfExists: replaceIfExists);

        // Assert
        Assert.Equal(replaceIfExists, command.CommandText.Contains("OR REPLACE"));

        Assert.Contains($"INTO \"{TableName}\" (\"Id\", \"Name\", \"Age\", \"Address\")", command.CommandText);
        Assert.Contains("VALUES (@Id, @Name, @Age, @Address)", command.CommandText);
        Assert.DoesNotContain("RETURNING", command.CommandText);

        Assert.Equal("@Id", command.Parameters[0].ParameterName);
        Assert.Null(command.Parameters[0].Value);

        Assert.Equal("@Name", command.Parameters[1].ParameterName);
        Assert.Null(command.Parameters[1].Value);

        Assert.Equal("@Age", command.Parameters[2].ParameterName);
        Assert.Null(command.Parameters[2].Value);

        Assert.Equal("@Address", command.Parameters[3].ParameterName);
        Assert.Null(command.Parameters[3].Value);
    }

    [Theory]
    [InlineData(true)]
    [InlineData(false)]
    public void ItBuildsInsertCommand_with_autogenerated_key(bool replaceIfExists)
    {
        // Arrange
        const string TableName = "TestTable";

        var model = BuildModel(
        [
            new VectorStoreKeyProperty("Id", typeof(int)),
            new VectorStoreDataProperty("Name", typeof(string)),
            new VectorStoreDataProperty("Age", typeof(string)),
            new VectorStoreDataProperty("Address", typeof(string)),
        ]);

        var records = new List<Dictionary<string, object?>>
        {
            new() { ["Id"] = default(int), ["Name"] = "NameValue1", ["Age"] = "AgeValue1", ["Address"] = "AddressValue1" },
            new() { ["Id"] = default(int), ["Name"] = "NameValue2", ["Age"] = "AgeValue2", ["Address"] = "AddressValue2" },
        };

        // Act
        var command = SqliteCommandBuilder.BuildInsertCommand(
            this._connection,
            TableName,
            model,
            data: true,
            isRecordKeyDatabaseGenerated: true,
            replaceIfExists: replaceIfExists);

        // Assert
        Assert.DoesNotContain("OR REPLACE", command.CommandText);

        Assert.Contains($"INTO \"{TableName}\" (\"Name\", \"Age\", \"Address\")", command.CommandText);
        Assert.Contains("VALUES (@Name, @Age, @Address)", command.CommandText);
        Assert.Contains("RETURNING \"Id\"", command.CommandText);

        Assert.Equal("@Name", command.Parameters[0].ParameterName);
        Assert.Null(command.Parameters[0].Value);
    }

    [Fact]
    public void ItSetsInsertParameterValues_for_data_properties()
    {
        // Arrange
        var model = BuildModel(
        [
            new VectorStoreKeyProperty("Id", typeof(string)),
            new VectorStoreDataProperty("Name", typeof(string)),
        ]);

        var record = new Dictionary<string, object?> { ["Id"] = "KeyValue", ["Name"] = "NameValue" };

        var command = SqliteCommandBuilder.BuildInsertCommand(this._connection, "TestTable", model, data: true, isRecordKeyDatabaseGenerated: false);
        var properties = SqliteCommandBuilder.GetInsertProperties(model, data: true);

        // Act
        SqliteCommandBuilder.SetInsertParameterValues(command, properties, isRecordKeyDatabaseGenerated: false, record);

        // Assert
        Assert.Equal("KeyValue", command.Parameters["@Id"].Value);
        Assert.Equal("NameValue", command.Parameters["@Name"].Value);
    }

    [Fact]
    public void ItSetsInsertParameterValues_converts_vectors_to_blobs()
    {
        // Arrange
        var model = BuildModel(
        [
            new VectorStoreKeyProperty("Id", typeof(string)),
            new VectorStoreVectorProperty("Embedding", typeof(ReadOnlyMemory<float>), 2),
        ]);

        float[] embeddings = [1f, 2f];
        var record = new Dictionary<string, object?> { ["Id"] = "KeyValue", ["Embedding"] = new ReadOnlyMemory<float>(embeddings) };

        var command = SqliteCommandBuilder.BuildInsertCommand(this._connection, "VectorTable", model, data: false, isRecordKeyDatabaseGenerated: false);
        var properties = SqliteCommandBuilder.GetInsertProperties(model, data: false);

        // Act
        SqliteCommandBuilder.SetInsertParameterValues(command, properties, isRecordKeyDatabaseGenerated: false, record);

        // Assert
        Assert.Equal(FloatToBytes(embeddings), (byte[])command.Parameters["@Embedding"].Value!);
    }

    [Fact]
    public void ItSetsInsertParameterValues_uses_generated_embeddings_by_record_index()
    {
        // Arrange
        var model = BuildModel(
        [
            new VectorStoreKeyProperty("Id", typeof(string)),
            new VectorStoreVectorProperty("Embedding", typeof(ReadOnlyMemory<float>), 2),
        ]);

        var record = new Dictionary<string, object?> { ["Id"] = "Key2", ["Embedding"] = new ReadOnlyMemory<float>([1f, 1f]) };

        var vectorProperty = model.VectorProperties.Single(v => v.StorageName == "Embedding");

        var embeddings = new ReadOnlyMemory<float>([7f, 7f]);
        var generatedEmbeddings = new Dictionary<VectorPropertyModel, IReadOnlyList<Embedding<float>>>
        {
            [vectorProperty] = [new(new float[] { 9f, 9f }), new(embeddings)],
        };

        var command = SqliteCommandBuilder.BuildInsertCommand(this._connection, "VectorTable", model, data: false, isRecordKeyDatabaseGenerated: false);
        var properties = SqliteCommandBuilder.GetInsertProperties(model, data: false);

        // Act
        SqliteCommandBuilder.SetInsertParameterValues(command, properties, isRecordKeyDatabaseGenerated: false, record, recordIndex: 1, generatedEmbeddings);

        // Assert - The generated embedding at the record's batch index should be used instead of the value in the record's Embedding property.
        Assert.Equal(SqlitePropertyMapping.MapVectorForStorageModel(embeddings), (byte[])command.Parameters["@Embedding"].Value!);
    }

    [Fact]
    public void ItSetsInsertParameterValues_generates_missing_guid_keys()
    {
        // Arrange
        var model = BuildModel(
        [
            new VectorStoreKeyProperty("Id", typeof(Guid)),
            new VectorStoreDataProperty("Name", typeof(string)),
        ]);

        var record = new Dictionary<string, object?> { ["Id"] = Guid.Empty, ["Name"] = "NameValue" };

        var command = SqliteCommandBuilder.BuildInsertCommand(this._connection, "TestTable", model, data: true, isRecordKeyDatabaseGenerated: false);
        var properties = SqliteCommandBuilder.GetInsertProperties(model, data: true);

        // Act
        SqliteCommandBuilder.SetInsertParameterValues(command, properties, isRecordKeyDatabaseGenerated: false, record);

        // Assert
        var generatedKey = Assert.IsType<Guid>(command.Parameters["@Id"].Value);
        Assert.NotEqual(Guid.Empty, generatedKey);
        Assert.Equal(generatedKey, record["Id"]);
    }

    [Fact]
    public void ItSetsInsertParameterValues_skips_database_generated_keys()
    {
        // Arrange
        var model = BuildModel(
        [
            new VectorStoreKeyProperty("Id", typeof(int)),
            new VectorStoreDataProperty("Name", typeof(string)),
        ]);

        var record = new Dictionary<string, object?> { ["Id"] = 0, ["Name"] = "NameValue" };

        var command = SqliteCommandBuilder.BuildInsertCommand(this._connection, "TestTable", model, data: true, isRecordKeyDatabaseGenerated: true);
        var properties = SqliteCommandBuilder.GetInsertProperties(model, data: true);

        // Act
        SqliteCommandBuilder.SetInsertParameterValues(command, properties, isRecordKeyDatabaseGenerated: true, record);

        // Assert
        // The key column is omitted from the statement, so only the data parameters are bound.
        Assert.Single(command.Parameters);
        Assert.Equal("NameValue", command.Parameters["@Name"].Value);
        Assert.Equal(0, record["Id"]);
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("Age")]
    public void ItBuildsSelectCommand(string? orderByPropertyName)
    {
        // Arrange
        const string TableName = "TestTable";

        var model = BuildModel(
        [
            new VectorStoreKeyProperty("Id", typeof(string)),
            new VectorStoreDataProperty("Name", typeof(string)),
            new VectorStoreDataProperty("Age", typeof(string)),
            new VectorStoreDataProperty("Address", typeof(string)),
        ]);
        var conditions = new List<SqliteWhereCondition>
        {
            new SqliteWhereEqualsCondition("Name", "NameValue"),
            new SqliteWhereInCondition("Age", [10, 20, 30]),
        };
        FilteredRecordRetrievalOptions<Dictionary<string, object?>> filterOptions = new();
        if (!string.IsNullOrWhiteSpace(orderByPropertyName))
        {
            filterOptions.OrderBy = orderBy => orderBy.Ascending(record => record[orderByPropertyName]);
        }

        // Act
        var command = SqliteCommandBuilder.BuildSelectDataCommand<Dictionary<string, object?>>(this._connection, TableName, model, conditions, filterOptions);

        // Assert
        Assert.Contains("SELECT \"Id\",\"Name\",\"Age\",\"Address\"", command.CommandText);
        Assert.Contains($"FROM \"{TableName}\"", command.CommandText);

        Assert.Contains("\"Name\" = @Name0", command.CommandText);
        Assert.Contains("\"Age\" IN (@Age0, @Age1, @Age2)", command.CommandText);

        Assert.Equal(!string.IsNullOrWhiteSpace(orderByPropertyName), command.CommandText.Contains($"ORDER BY \"{orderByPropertyName}\""));

        Assert.Equal("@Name0", command.Parameters[0].ParameterName);
        Assert.Equal("NameValue", command.Parameters[0].Value);

        Assert.Equal("@Age0", command.Parameters[1].ParameterName);
        Assert.Equal(10, command.Parameters[1].Value);

        Assert.Equal("@Age1", command.Parameters[2].ParameterName);
        Assert.Equal(20, command.Parameters[2].Value);

        Assert.Equal("@Age2", command.Parameters[3].ParameterName);
        Assert.Equal(30, command.Parameters[3].Value);
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("Age")]
    public void ItBuildsSelectInnerJoinCommand(string? orderByPropertyName)
    {
        // Arrange
        const string DataTable = "DataTable";
        const string VectorTable = "VectorTable";
        const string JoinColumnName = "Id";

        var model = BuildModel(
        [
            new VectorStoreKeyProperty("Id", typeof(string)),
            new VectorStoreDataProperty("Name", typeof(string)),
            new VectorStoreVectorProperty("Age", typeof(ReadOnlyMemory<float>), 10),
            new VectorStoreVectorProperty("Address", typeof(ReadOnlyMemory<float>), 10),
        ]);

        var conditions = new List<SqliteWhereCondition>
        {
            new SqliteWhereEqualsCondition("Name", "NameValue"),
            new SqliteWhereInCondition("Age", [10, 20, 30]),
        };
        FilteredRecordRetrievalOptions<Dictionary<string, object?>> filterOptions = new();
        if (!string.IsNullOrWhiteSpace(orderByPropertyName))
        {
            filterOptions.OrderBy = orderBy => orderBy.Ascending(record => record[orderByPropertyName]);
        }

        // Act
        var command = SqliteCommandBuilder.BuildSelectInnerJoinCommand(
            this._connection,
            VectorTable,
            DataTable,
            JoinColumnName,
            model,
            conditions,
            true,
            filterOptions);

        // Assert
        Assert.Contains("SELECT \"DataTable\".\"Id\",\"DataTable\".\"Name\",\"VectorTable\".\"Age\",\"VectorTable\".\"Address\"", command.CommandText);
        Assert.Contains("FROM \"VectorTable\"", command.CommandText);

        Assert.Contains("INNER JOIN \"DataTable\" ON \"VectorTable\".\"Id\" = \"DataTable\".\"Id\"", command.CommandText);

        Assert.Contains("\"Name\" = @Name0", command.CommandText);
        Assert.Contains("\"Age\" IN (@Age0, @Age1, @Age2)", command.CommandText);

        Assert.Equal(!string.IsNullOrWhiteSpace(orderByPropertyName), command.CommandText.Contains($"ORDER BY \"DataTable\".\"{orderByPropertyName}\""));

        Assert.Equal("@Name0", command.Parameters[0].ParameterName);
        Assert.Equal("NameValue", command.Parameters[0].Value);

        Assert.Equal("@Age0", command.Parameters[1].ParameterName);
        Assert.Equal(10, command.Parameters[1].Value);

        Assert.Equal("@Age1", command.Parameters[2].ParameterName);
        Assert.Equal(20, command.Parameters[2].Value);

        Assert.Equal("@Age2", command.Parameters[3].ParameterName);
        Assert.Equal(30, command.Parameters[3].Value);
    }

    [Fact]
    public void ItBuildsDeleteCommand()
    {
        // Arrange
        const string TableName = "TestTable";

        var conditions = new List<SqliteWhereCondition>
        {
            new SqliteWhereEqualsCondition("Name", "NameValue"),
            new SqliteWhereInCondition("Age", [10, 20, 30]),
        };

        // Act
        var command = SqliteCommandBuilder.BuildDeleteCommand(this._connection, TableName, conditions);

        // Assert
        Assert.Contains("DELETE FROM \"TestTable\"", command.CommandText);

        Assert.Contains("\"Name\" = @Name0", command.CommandText);
        Assert.Contains("\"Age\" IN (@Age0, @Age1, @Age2)", command.CommandText);

        Assert.Equal("@Name0", command.Parameters[0].ParameterName);
        Assert.Equal("NameValue", command.Parameters[0].Value);

        Assert.Equal("@Age0", command.Parameters[1].ParameterName);
        Assert.Equal(10, command.Parameters[1].Value);

        Assert.Equal("@Age1", command.Parameters[2].ParameterName);
        Assert.Equal(20, command.Parameters[2].Value);

        Assert.Equal("@Age2", command.Parameters[3].ParameterName);
        Assert.Equal(30, command.Parameters[3].Value);
    }

    [Fact]
    public void ItBuildsDeleteByKeyCommand()
    {
        // Arrange
        const string TableName = "TestTable";
        const string KeyName = "Id";

        // Act
        var command = SqliteCommandBuilder.BuildDeleteByKeyCommand(this._connection, TableName, KeyName);

        // Assert
        Assert.Equal("DELETE FROM \"TestTable\" WHERE \"Id\" = " + SqliteCommandBuilder.KeyParameterName, command.CommandText);

        Assert.Equal(SqliteCommandBuilder.KeyParameterName, command.Parameters[0].ParameterName);
        Assert.Null(command.Parameters[0].Value);
    }

    public void Dispose()
    {
        this._command.Dispose();
        this._connection.Dispose();
    }

    private static CollectionModel BuildModel(List<VectorStoreProperty> properties)
        => new SqliteModelBuilder()
            .BuildDynamic(new() { Properties = properties }, defaultEmbeddingGenerator: null);

    private static byte[] FloatToBytes(params float[] values)
    {
        var bytes = new byte[values.Length * sizeof(float)];
        for (var i = 0; i < values.Length; i++)
        {
            BitConverter.GetBytes(values[i]).CopyTo(bytes, i * sizeof(float));
        }

        return bytes;
    }
}
